name = "cubicsplines"
version = "0.1.0"
license = "license"
author = "Thomas"
maintainer = "thomas.biekoetter@desy.de"
copyright = "Copyright 2026, Thomas"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = true
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[[test]]
name = "trigo"
source-dir = "test"
main = "trigo.f90"
[[test]]
name = "smoothing"
source-dir = "test"
main = "smoothing.f90"
[[test]]
name = "const"
source-dir = "test"
main = "const.f90"
[test.dependencies]
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }
[features]
debug.flags = "-g -O0 -fPIC"
debug.gfortran.flags = "-fmax-errors=1 -ffixed-line-length-none -Wall -Wimplicit-interface -Wall -Wno-integer-division -fbounds-check -ffpe-trap=invalid,zero,overflow"
debug.ifx.flags = "-DUSING_IFX -check bounds -check pointer -traceback -debug all"
release.flags = "-O3 -fPIC"
release.gfortran.flags = "-march=native -fmax-errors=1 -ffixed-line-length-none -fno-range-check"
release.ifx.flags = "-DUSING_IFX -xHost"
coverage.gfortran.flags = "-DDEBUG -O0 -fPIC -fPIE --coverage"
[profiles]
debug = ["debug"]
release = ["release"]
coverage = ["coverage"]

